---

- name: Load OS-specific vars
  include_vars: "{{lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "../../group_vars/linux/{{ ansible_facts['os_family'] }}.yml"

#
# - name: see if group_vars worked
#   debug:
#     msg: "{{ kafka_service_rules }}"
#

- name: Set SELinux to permissive
  ansible.posix.selinux:
    policy: targeted
    state: permissive

# must not use quotes in the block: section
- name: insert service-specific iptables rules
  blockinfile:
    block: |
      {{ kafka_service_rules }}
    path: "{{ iptables_path }}"
    insertafter: "## BEGIN HOST-SPECIFIC RULES"
  notify: load iptables rules
  ignore_errors: yes

- name: create kafka user
  user:
    name: kafka
    shell: /bin/false

- name: install openjdk and related pkgs
  dnf:
    name: "{{ pkgs }}"
    state: latest
  vars:
    pkgs:
    - java-latest-openjdk-headless
    - java-latest-openjdk-src

- name: build kafka directory structures
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
    mode: 0750
    recurse: yes
  loop:
    - "{{ kafka_path }}/kafka_{{scala_vers}}-{{kafka_vers}}/logs/kraft-combined-logs"
    - "{{ kafka_log_dir }}"

# https://downloads.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz
- name: download kafka source
  get_url:
    url: "https://downloads.apache.org/kafka/{{kafka_vers}}/kafka_{{scala_vers}}-{{kafka_vers}}.tgz"
    dest: /tmp/kafka_{{scala_vers}}-{{kafka_vers}}.tgz

- name: expand tarball to source folder
  unarchive:
    src: "/tmp/kafka_{{scala_vers}}-{{kafka_vers}}.tgz"
    dest: "{{ kafka_path }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0640
  notify: enforce kafka permissions

- name: symlink kafka dirs to latest
  file:
    state: link
    src: "{{ kafka_path }}/kafka_{{scala_vers}}-{{kafka_vers}}"
    dest: "{{ kafka_path }}/latest"

- name: set execute bit on files in bin dir
  file:
    path: "{{ kafka_path }}/kafka_{{scala_vers}}-{{kafka_vers}}/bin/"
    state: directory
    mode: 0750
    recurse: yes

- name: install kafka service systemd unit file
  template:
    src: ../templates/confluent-server.service.j2
    dest: /etc/systemd/system/confluent-server.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: render kakfa service config file
  template:
    src: ../templates/server.properties.j2
    dest: "{{ kafka_path }}/latest/config/kraft/server.properties"
    owner: kafka
    group: kafka
    mode: 0640
    backup: yes
  notify: restart kafka service

- name: add kafka bin path to all users' PATH
  template:
    src: ../templates/kafka_path.sh.j2
    dest: /etc/profile.d/kafka_path.sh
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: bin_t
    selevel: s0

- name: check if kraft logs dir has been initialized
  shell: "{{ kafka_path }}/latest/bin/kafka-storage.sh info -c {{ kafka_path }}/latest/config/kraft/server.properties"
  register: storage_init
  ignore_errors: yes

- name: init kraft logs dir
  shell: "{{ kafka_path }}/kafka_{{scala_vers}}-{{kafka_vers}}/bin/kafka-storage.sh format -t {{ kafka_cluster_id }} -c {{ kafka_path }}/kafka_{{scala_vers}}-{{kafka_vers}}/config/kraft/server.properties"
  when: '"is not formatted" in storage_init.stdout'

- name: start and enable kafka service service
  systemd:
    name: confluent-server
    state: started
    enabled: yes


# - name: install zookeeper systemd unit file
#   template:
#     src: ../templates/confluent-zookeeper.service.j2
#     dest: /etc/systemd/system/confluent-zookeeper.service
#     owner: root
#     group: root
#     mode: 0644
#   notify: reload systemd
#
# - name: render zookeeper config file
#   template:
#     src: ../templates/zookeeper.properties.j2
#     dest: "{{ kafka_path }}/latest/config/zookeeper.properties"
#     owner: kafka
#     group: kafka
#     mode: 0640
#     backup: yes
#   notify: restart zookeeper
#
# - name: start and enable zookeeper service
#   systemd:
#     name: confluent-zookeeper
#     state: started
#     enabled: yes



...
